on:
  workflow_dispatch:
  schedule:
    - cron: 0 15 * * * # everyday 00:00 JST (Midnight)

jobs:
  update-devenv:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - uses: cachix/install-nix-action@0b0e072294b088b73964f1d72dfdac0951439dbd # v31.8.4
      - uses: cachix/cachix-action@0fc020193b5a1fa3ac4575aa3a7d3aa6a35435ad # v16
        with:
          name: devenv

      - name: update-devenv
        shell: bash
        run: |
          nix profile install nixpkgs#devenv
          devenv update

      - name: git-commit
        env:
          GIT_AUTHOR_NAME: "Peacock"
          GIT_AUTHOR_EMAIL: "33555487+peacock0803sz@users.noreply.github.com"
          GIT_COMMITTER_NAME: "github-actions[bot]"
          GIT_COMMITTER_EMAIL: "github-actions[bot]@users.noreply.github.com"
        run: |
          if (( $(git status --short --untracked-files | wc -l) < 1 )); then exit 0; fi
          git add devenv.lock
          git commit -m ":snowflake: Update devenv.lock"
          git push origin HEAD
