on:
  workflow_dispatch:
  schedule:
    - cron: 0 15 * * * # everyday 00:00 JST (Midnight)

jobs:
  update-devenv:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: cachix/install-nix-action@4e002c8ec80594ecd40e759629461e26c8abed15 # v31.9.0
      - uses: cachix/cachix-action@3ba601ff5bbb07c7220846facfa2cd81eeee15a1 # v16
        with:
          name: devenv

      - name: update-devenv
        shell: bash
        run: |
          nix profile install nixpkgs#devenv
          devenv update

      - name: git-commit
        env:
          GIT_AUTHOR_NAME: "Peacock"
          GIT_AUTHOR_EMAIL: "33555487+peacock0803sz@users.noreply.github.com"
          GIT_COMMITTER_NAME: "github-actions[bot]"
          GIT_COMMITTER_EMAIL: "github-actions[bot]@users.noreply.github.com"
        run: |
          if (( $(git status --short --untracked-files | wc -l) < 1 )); then exit 0; fi
          git add devenv.lock
          git commit -m ":snowflake: Update devenv.lock"
          git push origin HEAD
